#include <tesseract_common/cereal_serialization.h>

// These must be include before calling macro CEREAL_REGISTER_TYPE
#include <cereal/archives/binary.hpp>
#include <cereal/archives/xml.hpp>
#include <cereal/archives/json.hpp>

CEREAL_REGISTER_TYPE(tesseract::common::BoolAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::IntAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UnsignedAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::DoubleAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::FloatAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::StringAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::SizeTAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorStringAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorBoolAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorIntAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorUnsignedAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorDoubleAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorFloatAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::VectorSizeTAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringStringAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringBoolAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringIntAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringUnsignedAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringDoubleAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringFloatAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::UMapStringSizeTAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::ACMContactAllowedValidator)
CEREAL_REGISTER_TYPE(tesseract::common::CombinedContactAllowedValidator)
CEREAL_REGISTER_TYPE(tesseract::common::JointStateAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::JointStatePtrAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::ManipulatorInfoAnyPoly)
CEREAL_REGISTER_TYPE(tesseract::common::Resource)
CEREAL_REGISTER_TYPE(tesseract::common::GeneralResourceLocator)
CEREAL_REGISTER_TYPE(tesseract::common::SimpleLocatedResource)
CEREAL_REGISTER_TYPE(tesseract::common::BytesResource)
CEREAL_REGISTER_TYPE(tesseract::common::ProfileDictionaryPtrAnyPoly)

CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::BoolAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::IntAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UnsignedAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::DoubleAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::FloatAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::StringAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::SizeTAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorStringAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorBoolAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorIntAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorUnsignedAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorDoubleAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorFloatAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::VectorSizeTAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringStringAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringBoolAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringIntAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringUnsignedAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringDoubleAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringFloatAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::UMapStringSizeTAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::ContactAllowedValidator,
                                     tesseract::common::ACMContactAllowedValidator)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::ContactAllowedValidator,
                                     tesseract::common::CombinedContactAllowedValidator)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::JointStateAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::JointStatePtrAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::ManipulatorInfoAnyPoly)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::ResourceLocator, tesseract::common::Resource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::ResourceLocator, tesseract::common::GeneralResourceLocator)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::Resource, tesseract::common::SimpleLocatedResource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::Resource, tesseract::common::BytesResource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(tesseract::common::AnyInterface, tesseract::common::ProfileDictionaryPtrAnyPoly)

// LCOV_EXCL_START
CEREAL_REGISTER_DYNAMIC_INIT(tesseract_common_cereal)
// LCOV_EXCL_STOP
