set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_PLATFORM_TOOLSET "v142")
set(VCPKG_DEP_INFO_OVERRIDE_VARS "v142")

set(VCPKG_CXX_FLAGS_RELEASE "/MD /O0 /Ob0 /Zi /DNDEBUG /FS")
set(VCPKG_C_FLAGS_RELEASE "/MD /O0 /Ob0 /Zi /DNDEBUG /FS")
set(VCPKG_LINK_FLAGS_RELEASE "/DEBUG /INCREMENTAL:NO")