tesseract_msgs/ProcessPlanPath from_start                # Freespace motion from home to start of segment 0
tesseract_msgs/ProcessPlanSegment[] segments             # All of the raster segments with approaches and departures
tesseract_msgs/ProcessPlanTransitionPair[] transitions   # Freespace/Cartesian motions to transition between the segments
tesseract_msgs/ProcessPlanPath to_end                    # Freespae motioin from end of the last segment to home

