# You can combine the requests using a bitwise OR operation (In C++, use
# the | operator).  They are extracted from the `flags` variable using a
# bitwise AND operator.
uint16 COMMAND_HISTORY=1             # Get the current change history

uint16 LINK_LIST=2                   # Get the current list of links
uint16 JOINT_LIST=4                  # Get the current list of links

uint16 LINK_NAMES=8                  # Get the current list of links
uint16 JOINT_NAMES=16                # Get the current list of links

uint16 ACTIVE_LINK_NAMES=32          # Get the current list of active links
uint16 ACTIVE_JOINT_NAMES=64         # Get the current list of active joints

uint16 LINK_TRANSFORMS=128           # Get the current list of link transforms
uint16 JOINT_TRANSFORMS=256          # Get the current list of joint transforms

uint16 ALLOWED_COLLISION_MATRIX=512  # Get the current list of joint transforms

uint16 flags # The flags indicating what information should be returned.
---
bool success
string id # Name/Id of the environment
uint64 revision # The revision number of the modified environment, these should match after applying commands to local copy of environment

tesseract_msgs/EnvironmentCommand[] command_history
tesseract_msgs/Link[] links
tesseract_msgs/Joint[] joints
string[] link_names
string[] joint_names
string[] active_link_names
string[] active_joint_names
tesseract_msgs/TransformMap link_transforms
tesseract_msgs/TransformMap joint_transforms
tesseract_msgs/AllowedCollisionEntry[] allowed_collision_matrix
