string id # Name/Id of the environment
uint64 revision # The revision number from which these commands should be applied
tesseract_msgs/EnvironmentCommand[] commands
---
bool success
uint64 revision # New id to store for checking if environment has changed
