name: Conda

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
    paths:
      - 'tesseract**'
      - '.github/workflows/conda.yml'
      - '**.repos'
  release:
    types:
      - released

jobs:
  conda-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
    - uses: actions/checkout@v4
      with:
       path: workspace/src/tesseract
    - name: install-depends
      shell: cmd
      run: |
        python -m pip install vcstool -q
    - name: vcs import
      run: >
        vcs import --input "${{ github.workspace }}/workspace/src/tesseract/.github/workflows/windows_dependencies.repos" workspace/src/
    - uses: conda-incubator/setup-miniconda@v3
      with:
        channel-priority: strict
        environment-file: workspace/src/tesseract/.github/workflows/conda/environment.yml
        activate-environment: tesseract-build
        channels: conda-forge
        conda-remove-defaults: "true"
    - name: build and test
      run: |
        conda info
        conda list

        mkdir conda
        xcopy /E workspace\src\tesseract\.github\workflows\conda conda
        cd conda
        New-Item -Name conda-forge.yml -ItemType File
        conda smithy regenerate
        
        conda build -m .ci_support/win_64_.yaml --build-only .

  conda-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
      with:
        path: workspace/src/tesseract
    - name: install-depends
      run: |
        python -m pip install vcstool -q
    - name: vcs import
      run: >
        vcs import --input "${{ github.workspace }}/workspace/src/tesseract/.github/workflows/windows_dependencies.repos" workspace/src/
    - uses: conda-incubator/setup-miniconda@v3
      with:
        channel-priority: strict
        environment-file: workspace/src/tesseract/.github/workflows/conda/environment.yml
        activate-environment: tesseract-build
        channels: conda-forge
        conda-remove-defaults: "true"
    - name: build and test
      run: |
        conda info
        conda list
        
        cp -r workspace/src/tesseract/.github/workflows/conda ./conda
        cd conda
        touch conda-forge.yml
        conda smithy regenerate
        
        conda build -m .ci_support/linux_64_.yaml --build-only .

  conda-mac:
    runs-on: macos-13
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
      with:
        path: workspace/src/tesseract
    - name: install-depends
      run: |
        python -m pip install vcstool -q
    - name: vcs import
      run: >
        vcs import --input "${{ github.workspace }}/workspace/src/tesseract/.github/workflows/windows_dependencies.repos" workspace/src/
    - uses: conda-incubator/setup-miniconda@v3
      with:
        channel-priority: strict
        environment-file: workspace/src/tesseract/.github/workflows/conda/environment.yml
        activate-environment: tesseract-build
        channels: conda-forge
        conda-remove-defaults: "true"
    - name: build and test
      run: |
        conda info
        conda list
        
        cp -r workspace/src/tesseract/.github/workflows/conda ./conda
        cd conda
        touch conda-forge.yml
        conda smithy regenerate
        
        conda build -m .ci_support/osx_64_.yaml --build-only .
